engines:
  duplication:
    enabled: true
    config:
      languages:
        - php

  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR2"

  phpmd:
    enabled: true

ratings:
  paths:
    - "**.php"

exclude_paths:
  - "tests/"
  - "**.md"
  - "**.json"
  - "**.xml"
  - "**.dist"
